# Generated by Django 4.1.2 on 2023-01-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_user_subject_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.TextField(verbose_name='Информационный текст1')),
                ('second_text', models.TextField(verbose_name='Информационный текст2')),
                ('third_text', models.TextField(verbose_name='Информационный текст3')),
            ],
        ),
    ]
