# Generated by Django 4.1.5 on 2023-02-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_information_about_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Information_About",
        ),
    ]
