# Generated by Django 4.1.5 on 2023-02-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_delete_information_about"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="url",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
