# Generated by Django 4.1.5 on 2023-02-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_category_url_delete_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
            ),
        ),
    ]
