# Generated by Django 4.1.5 on 2023-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_subject_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="photo/category/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="photo/subject/", verbose_name="Изображение"
            ),
        ),
    ]
